.\" Manpage for git-source
.TH git-source 1 "March 2026" "git-fetcher"
.SH NAME
git-source, gsrc \- fetch archives and tags from Git repositories

.SYNOPSIS
.B git-source, gsrc
[\fIOPTIONS\fR] <repo_url_or_owner/repo>

.B gsrc
[\fIOPTIONS\fR] <repo_url_or_owner/repo>

.SH DESCRIPTION
This command fetches the latest tags, archives, or branches from GitHub, GitLab, Bitbucket, or Googlesource repositories.
Both \fBgit-source\fR and \fBgsrc\fR point to the same executable.

The tool automatically detects the host from the URL and fetches the latest tag or default branch.
Downloaded archives are saved under the \fBdownloads/\fR directory.

.SH OPTIONS
.TP
.B -b, --list-branches
List all branches of the repository and exit.

.TP
.B -v, --verbose
Show verbose messages for informational purposes.

.TP
.B --debug
Show debug messages for developers.

.TP
.B -h, --help
Show a short help message.

.SH EXAMPLES
.TP
Download the latest GitHub release:
$ git-source https://github.com/alembic/alembic

.TP
List all branches of a GitLab repository:
$ git-source -b https://gitlab.com/oscore/liboscore

.TP
Download with verbose messages:
$ git-source -v https://github.com/google/farmhash

.SH NOTES
Googlesource repositories generate tarballs dynamically. The SHA256 checksum may differ
between downloads even when the source code has not changed.

.SH AUTHOR
Written by Harry Kunz aka Harry McKenzie

.SH SEE ALSO
git(1), curl(1), jq(1)


The tool automatically detects the host from the URL and fetches the latest tag or default branch.
Downloaded archives are saved under the \fBdownloads/\fR directory.

.SH OPTIONS
.TP
.B -b, --list-branches
List all branches of the repository and exit.

.TP
.B -v, --verbose
Show verbose messages for informational purposes.

.TP
.B --debug
Show debug messages for developers.

.TP
.B -h, --help
Show a short help message.

.SH EXAMPLES
.TP
Download the latest GitHub release:
$ git-source https://github.com/alembic/alembic

.TP
List all branches of a GitLab repository:
$ git-source -b https://gitlab.com/oscore/liboscore

.TP
Download with verbose messages:
$ git-source -v https://github.com/google/farmhash

.SH NOTES
Googlesource repositories generate tarballs dynamically. The SHA256 checksum may differ
between downloads even when the source code has not changed.

.SH AUTHOR
Written by Harry McKenzie

.SH SEE ALSO
git(1), curl(1), jq(1)
