.\" Manpage for git-source
.TH git-source 1 "March 2026" "git-fetcher"
.SH NAME
git-source, gsrc \- fetch archives and tags from Git repositories

.SH SYNOPSIS
.B git-source, gsrc
[\fIOPTIONS\fR] <repo_url_or_owner/repo>

.B gsrc
[\fIOPTIONS\fR] <repo_url_or_owner/repo>

.SH DESCRIPTION
This command fetches the latest tags, archives, or branches from GitHub, GitLab, Bitbucket, or Googlesource repositories.
Both \fBgit-source\fR and \fBgsrc\fR point to the same executable.

The tool automatically detects the host from the URL and fetches the latest tag or default branch.
Downloaded archives are saved under the \fBdownloads/\fR directory.

.SH OPTIONS
.TP
.B -b, --list-branches
List all branches of the repository and exit.

.TP
.B -t, --list-tags
List all tags of the repository and exit.

.TP
.B -v, --verbose
Show verbose informational messages.

.TP
.B --debug
Show debug messages for developers.

.TP
.B -h, --help
Show this help message.

.TP
.B --tag <name>
Download a specific tag from the repository.

.TP
.B --branch <name>
Download a specific branch from the repository.

.TP
.B --commit <hash>
Download a specific commit from the repository.

.TP
.B --url-only
Skip host detection; treat the input as a direct archive URL.

.TP
.B --generate-mxe-makefile
Generate an MXE .mk file for the repository using the default library name.

.TP
.B --generate-mxe-makefile=<libname>
Generate an MXE .mk file for the repository, using the specified library name.

.SH EXAMPLES
.TP
Download the latest GitHub release:
$ git-source https://github.com/alembic/alembic

.TP
List all branches of a GitLab repository:
$ git-source -b https://gitlab.com/oscore/liboscore

.TP
Download with verbose messages:
$ git-source -v https://github.com/google/farmhash

.TP
Download a specific tag:
$ git-source https://github.com/libpng/libpng --tag=v1.0.67

.TP
Download a specific branch:
$ git-source https://github.com/libpng/libpng --branch=main

.TP
Download a specific commit:
$ git-source https://github.com/libpng/libpng --commit=43b7f9ad5e86e6dce2a4a6ec9d661ff8d35cc159

.TP
Download a direct archive URL (for unsupported or unknown hosts):
$ git-source https://example.com/project/releases/latest.tar.gz

.TP
Generate an MXE .mk file for default library:
$ git-source https://github.com/alembic/alembic --generate-mxe-makefile

.TP
Generate an MXE .mk file for a specific library:
$ git-source https://github.com/alembic/alembic --generate-mxe-makefile=alembic

.SH NOTES
Googlesource repositories generate tarballs dynamically. The SHA256 checksum may differ
between downloads even when the source code has not changed.

If using MXE integration, you can optionally set the \fBMXE_ROOT\fR environment variable to
your MXE root directory and \fBMXE_TARGET\fR to your target triplet. Generated .mk files
will then be automatically copied into \fBMXE_ROOT/src/\fR. Existing files will prompt
for overwrite.

.SH AUTHOR
Written by Harry Kunz aka Harry McKenzie

.SH SEE ALSO
git(1), curl(1), jq(1)
